openapi: 3.0.3
info:
  title: Ensi Backend Skeleton (Replace me)
  version: 1.0.0
  description: Ensi Backend Skeleton Description (Replace me)
servers:
  - url: /api/v1
tags:
  - name: examples
    description: Тэг-пример
paths:
  /categories:
    $ref: './categories.yaml#/paths/~1categories'
  /categories/{id}:
    $ref: './categories.yaml#/paths/~1categories~1{id}'
  /advertisements:
    $ref: './advertisements.yaml#/paths/~1advertisements'
  /advertisements/{id}:
    $ref: './advertisements.yaml#/paths/~1advertisements~1{id}'
  /favorites:
    $ref: './favorites.yaml#/paths/~1favorites'
  /favorites/{id}:
    $ref: './favorites.yaml#/paths/~1favorites~1{id}'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, for documentation purposes only
  schemas:
    CreateCategoryRequest:
      $ref: './components.yaml#/components/schemas/CreateCategoryRequest'
    UpdateCategoryRequest:
      $ref: './components.yaml#/components/schemas/UpdateCategoryRequest'
    CategoryResource:
      $ref: './components.yaml#/components/schemas/CategoryResource'
    CreateAdvertisementRequest:
      $ref: './components.yaml#/components/schemas/CreateAdvertisementRequest'
    UpdateAdvertisementRequest:
      $ref: './components.yaml#/components/schemas/UpdateAdvertisementRequest'
    AdvertisementResource:
      $ref: './components.yaml#/components/schemas/AdvertisementResource'
    CreateFavoriteRequest:
      $ref: './components.yaml#/components/schemas/CreateFavoriteRequest'
    FavoriteResource:
      $ref: './components.yaml#/components/schemas/FavoriteResource'
